title = 'My Game'
startMap = './main/maps/map'

modules = [
     './main',
    '@rpgjs/gamepad',
    '@rpgjs/title-screen'
]

[controls]
    [controls.up]
        repeat = true
        bind = 'up'

mongoDb = 'mongodb://localhost:27017/test'
    